name: restaurant_discovery_flutter
version: 1.0.0+1
publish_to: "none"

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  provider: ^6.1.2
  flutter_map: ^6.1.0
  latlong2: ^0.9.1
  url_launcher: ^6.3.0
  mobile_scanner: ^5.1.1
  intl: ^0.19.0

  firebase_core: ^4.4.0
  firebase_auth: ^6.1.4
  cloud_firestore: ^6.1.2
  firebase_analytics: ^12.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.3

flutter_icons:
  android: true
  ios: true
  image_path: "assets/restaure_logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/nftqr.png
